<?php
global $APPLICATION, $REQUESTS_TABLE_BODY_TEXT, $REQUESTS_TABLE_HEADER_TEXT;

$control = $APPLICATION->FUNCTIONS->REQUEST_CONTROL;
$RECORDS = $control->filterRecords(['status' => 2], true);
$ID = "request_id";
$BUTTON = -1;
?>
<?php include "public/views/pages/portal/account/structures/html_headings.phtml" ?>

<title>Dashboard</title>

<?php include "public/views/pages/portal/account/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/portal/account/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/portal/account/structures/html_right_heading.phtml" ?>

    <div class="right-body">

        <div class="data-table-main-container">
            <div class="data-table-header">
                <div class="left">
                    <div class="text">
                        <p>MY GALLERY</p>
                    </div>
                </div>
                <div class="right">
                    <div class="button-flex table-buttons">
                        <div class="text-button filled-button table-button show-component" data-name="view-request">
                            <div class="text">
                                <span>VIEW</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="download-request">
                            <div class="text">
                                <span>DOWNLOAD</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="data-table-body">
                <div class="gallery-images-container">
                    <?php foreach ($RECORDS as $RECORD): ?>
                        <div class="gallery-item" data-id="<?= $RECORD->request_id ?>" data-count="<?= count($RECORD->getResult()->images) ?>">
                            <div class="head">
                                <p><?= $RECORD->package->name . ' - ' . $RECORD->schedule?></p>
                                <span><?= count($RECORD->getResult()->images) . ' Images' ?></span>
                            </div>
                            <div class="body">
                                <div class="image-items">
                                    <?php foreach ($RECORD->getResult()->images as $image):  ?>
                                        <div class="image-item">
                                            <img src="/<?= $image->image ?>" alt="">
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

    </div>

    <?php include "public/views/pages/portal/account/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/lib/Stuk-jszip-2ceb998/dist/jszip.js"></script>
    <script type="module" src="/public/assets/scripts/lib/FileSaver.js-master/dist/FileSaver.js"></script>
    <script type="module" src="/public/assets/scripts/pages/main/user/gallery.js"></script>

    <?php include "public/views/pages/portal/account/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/portal/account/structures/html_body_closing.phtml" ?>
