<?php
global $APPLICATION;

$control = $APPLICATION->FUNCTIONS->INVENTORY_CONTROL;



?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Inventory</h1>
                </div>
                <div class="paragraph">
                    <p>Record all products at a time</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group">
                            <label for="">
                                <span>Inventory Date (* Optional)</span>
                            </label>
                            <div class="error-container">
                                <input type="datetime-local" name="inventory_date" placeholder="Inventory Date" >
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container">
                        <div class="form-group">
                            <label for="">
                                <span>Description</span>
                            </label>
                            <div class="error-container">
                                <textarea name="description" id="" cols="30" rows="10" placeholder="Enter product description"></textarea>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Confirm">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>