<?php
global $APPLICATION, $ALL_ITEM_STATUS;

$control = $APPLICATION->FUNCTIONS->INVENTORY_CONTROL;

$colors = $control->getAlRecordsWithDistinctColumn('color');
$sizes = $control->getAlRecordsWithDistinctColumn('size');
$categories = $control->getAlRecordsWithDistinctColumn('category');

$data = json_decode($_POST['data'], true);
$id = $data['id'];
$item = $control->get($id, false);

$ALL = [
    [
        "text" => "Normal",
        "value" => ItemStatus::NORMAL->value
    ],
    [
        "text" => "Damaged",
        "value" => ItemStatus::DAMAGED->value
    ],
    [
        "text" => "Borrowed",
        "value" => ItemStatus::BORROWED->value
    ],
    [
        "text" => "Lost",
        "value" => ItemStatus::LOST->value
    ],
];

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Item</h1>
                </div>
                <div class="paragraph">
                    <p>Display Item</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group">
                            <label for="">
                                <span>Item Name</span>
                            </label>
                            <div class="error-container">
                                <input type="text" name="name" placeholder="Name" value="<?= $item['name'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">
                                <span>Category</span>
                            </label>
                            <div class="error-container">
                                <?= CreateComboBox("category", "Category", $categories, false, $item['category']) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group">
                            <label for="">
                                <span>Stocks</span>
                            </label>
                            <div class="error-container">
                                <input type="number" name="stocks" placeholder="Stocks" value="<?= $item['stocks'] ?>">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">
                                <span>Size (Optional)</span>
                            </label>
                            <div class="error-container">
                                <?= CreateComboBox("size", "Size", $sizes, false, $item['size']) ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">
                                <span>Color (Optional)</span>
                            </label>
                            <div class="error-container">
                                <?= CreateComboBox("color", "Color", $colors, false, $item['color'], true) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container">
                        <div class="form-group">
                            <label for="">
                                <span>Description</span>
                            </label>
                            <div class="error-container">
                                <textarea name="description" id="" cols="30" rows="10" placeholder="Enter product description"><?= $item['description'] ?></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">
                            <span>Item Status</span>
                        </label>
                        <div class="error-container">
                            <?= CreateComboBox("item_status", "Item Status", $ALL, false, $ALL_ITEM_STATUS[$item['item_status'] - 1]) ?>
                        </div>
                    </div>

                    <div class="status-additional <?= $item['item_status'] == 1 ? 'hide-component' : '' ?>" style="margin-left: 20px">
                        <div class="form-group-container">
                            <div class="form-group">
                                <label for="">
                                    <span>Person Involved</span>
                                </label>
                                <div class="error-container">
                                    <input type="text" name="person_involved" placeholder="Person Involved"  value="<?= $item['person_involved'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">
                                    <span>Quantity Involved</span>
                                </label>
                                <div class="error-container">
                                    <input type="text" name="quantity_involved" placeholder="Quantity Involved"   value="<?= $item['quantity_involved'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">
                                    <span>Date Happened</span>
                                </label>
                                <div class="error-container">
                                    <input type="date" name="date_involved" placeholder="Date Happened"   value="<?= $item['date_involved'] ?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="">
                                    <span>Status Description</span>
                                </label>
                                <div class="error-container">
                                    <textarea name="status_description" id="" cols="30" rows="10" placeholder="Describe what happen"><?= $item['status_description'] ?></textarea>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <label for="">
                                <span>Image (Optional)</span>
                            </label>
                            <div class="error-container">
                                <input type="file" name="image" placeholder="Image" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save Changes">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>