<?php
global $APPLICATION, $ALL_ITEM_STATUS, $INVENTORY_REPORT_TABLE_HEADER_TEXT, $INVENTORY_REPORT_TABLE_BODY_TEXT;
global $ALL_ITEM_STATUS;

$control = $APPLICATION->FUNCTIONS->INVENTORY_REPORT_CONTROL;


$data = json_decode($_POST['data'], true);
$type = $data['type'];


function GetRecyclerBinData($type)
{
    global $APPLICATION, $USER_TABLE_HEADER_TEXT, $USER_TABLE_BODY_TEXT;
    global $PACKAGES_TABLE_BODY_TEXT, $PACKAGES_TABLE_HEADER_TEXT;
    global $INVENTORY_TABLE_HEADER_TEXT, $INVENTORY_TABLE_BODY_TEXT;
    global $WALKIN_TABLE_HEADER_TEXT, $WALKIN_TABLE_BODY_TEXT, $REQUEST_STATUS;
    global $ALL_ITEM_STATUS;

    switch ($type) {
        case TABLE_TYPE::ACCOUNTS->value:
            $control = $APPLICATION->FUNCTIONS->USER_CONTROL;

            $RECORDS = $control->filterRecordsReal(['user_type' => 1, "db_status" => DB_STATUS::REMOVED->value], false);
            $ID = "user_id";

            $RECORDS = array_map(function ($record) {
                $record['gender'] = ["Male", "Female"][$record['gender']];
                return $record;
            }, $RECORDS);

            $header = $USER_TABLE_HEADER_TEXT;
            $body = $USER_TABLE_BODY_TEXT;
            break;
        case TABLE_TYPE::PACKAGES->value:
            $control = $APPLICATION->FUNCTIONS->PACKAGE_CONTROL;
            $RECORDS = $control->filterRecordsReal(['db_status' => DB_STATUS::REMOVED->value], false);
            $ID = "package_id";

            $header = $PACKAGES_TABLE_HEADER_TEXT;
            $body = $PACKAGES_TABLE_BODY_TEXT;
            break;
        case TABLE_TYPE::INVENTORY_ITEM->value:
            $control = $APPLICATION->FUNCTIONS->INVENTORY_CONTROL;
            $RECORDS = $control->filterRecordsReal(['db_status' => DB_STATUS::REMOVED->value], false);
            $ID = "item_id";

            $RECORDS = array_map(function($record) use ($ALL_ITEM_STATUS) {
                $record['item_status'] = $ALL_ITEM_STATUS[$record['item_status'] - 1];
                return $record;
            }, $RECORDS);

            $header = $INVENTORY_TABLE_HEADER_TEXT;
            $body = $INVENTORY_TABLE_BODY_TEXT;
            break;
        case TABLE_TYPE::WALKIN_REQUEST->value:
            $control = $APPLICATION->FUNCTIONS->WALKIN_CONTROL;
            $RECORDS = $control->filterRecordsReal(['db_status' => DB_STATUS::REMOVED->value], false);
            $ID = "walkin_id";

            $RECORDS = array_map(function ($record) use ($REQUEST_STATUS) {
                $record->status = $REQUEST_STATUS[$record->status];

                return (Array) $record;
            }, $RECORDS);

            $header = $WALKIN_TABLE_HEADER_TEXT;
            $body = $WALKIN_TABLE_BODY_TEXT;
            break;
    }

    return [
        "header" => $header,
        "body" => $body,
        "records" => $RECORDS,
        "id" => $ID
    ];

}


$NEED_DATA = GetRecyclerBinData($type);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table go-large">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Inventory</h1>
                </div>
                <div class="paragraph">
                    <p>Inventory #</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="data-table-main-container" data-id="<?= $NEED_DATA['id'] ?>">
                        <div class="data-table-header">
                            <div class="left">
                                <div class="text">
                                    <p>WALK IN</p>
                                </div>
                            </div>
                            <div class="right">
                                <div class="button-flex table-buttons">
                                    <div class="text-button filled-button table-button show-component" data-name="restore-request">
                                        <div class="text">
                                            <span>RESTORE</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="data-table-body">
                            <?= CreateTable($NEED_DATA['header'], $NEED_DATA['body'], $NEED_DATA['records'], $NEED_DATA['id'], false, false) ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>