<?php
global $APPLICATION, $INVENTORY_TABLE_HEADER_TEXT, $INVENTORY_TABLE_BODY_TEXT, $INVENTORY_RECORD_TABLE_HEADER_TEXT, $INVENTORY_RECORD_TABLE_BODY_TEXT;
global $ALL_ITEM_STATUS;

$control = $APPLICATION->FUNCTIONS->INVENTORY_CONTROL;
$controlReport = $APPLICATION->FUNCTIONS->INVENTORY_REPORT_CONTROL;

$RECORDS = $control->getAllRecords(false);
$ID = "item_id";
$BUTTON = -1;

$ALLRECORDS = $controlReport->getAllRecords(false);
$REPORT_ID = $controlReport->getTablePrimaryID();

$RECORDS = array_map(function($record) use ($ALL_ITEM_STATUS) {
    $record['item_status'] = $ALL_ITEM_STATUS[$record['item_status'] - 1];
    return $record;
}, $RECORDS);
?>
<?php include "public/views/pages/portal/account/structures/html_headings.phtml" ?>

<title>Dashboard</title>

<?php include "public/views/pages/portal/account/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/portal/account/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/portal/account/structures/html_right_heading.phtml" ?>

    <div class="right-body">
        <div class="data-table-main-container main">
            <div class="data-table-header">
                <div class="left">
                    <div class="text">
                        <p>INVENTORY</p>
                    </div>
                </div>
                <div class="right">
                    <div class="button-flex table-buttons">
                        <div class="text-button filled-button table-button show-component" data-name="new-request">
                            <div class="text">
                                <span>NEW INVENTORY</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="delete-request">
                            <div class="text">
                                <span>REMOVE</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="edit-request">
                            <div class="text">
                                <span>UPDATE</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="add-request">
                            <div class="text">
                                <span>ADD</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="data-table-body">
                <?= CreateTable($INVENTORY_TABLE_HEADER_TEXT, $INVENTORY_TABLE_BODY_TEXT, $RECORDS, $ID, $BUTTON) ?>
            </div>
        </div>

        <div class="data-table-main-container inventory-records">
            <div class="data-table-header">
                <div class="left">
                    <div class="text">
                        <p>INVENTORY RECORDS</p>
                    </div>
                </div>
                <div class="right">
                    <div class="button-flex table-buttons">
                        <div class="text-button filled-button table-button show-component" data-name="view-request">
                            <div class="text">
                                <span>VIEW INVENTORY</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="data-table-body">
                <?= CreateTable($INVENTORY_RECORD_TABLE_HEADER_TEXT, $INVENTORY_RECORD_TABLE_BODY_TEXT, $ALLRECORDS, $REPORT_ID, $BUTTON) ?>
            </div>
        </div>

    </div>

    <?php include "public/views/pages/portal/account/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/main/admin/inventory.js"></script>

    <?php include "public/views/pages/portal/account/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/portal/account/structures/html_body_closing.phtml" ?>
