<?php
global $APPLICATION, $WALKIN_TABLE_HEADER_TEXT, $WALKIN_TABLE_BODY_TEXT, $REQUEST_STATUS;

$control = $APPLICATION->FUNCTIONS->WALKIN_CONTROL;
$RECORDS = $control->getAllRecords(true);
$ID = "walkin_id";
$BUTTON = -1;

$RECORDS = array_map(function ($record) use ($REQUEST_STATUS) {
    $record->status = $REQUEST_STATUS[$record->status];

    return (Array) $record;
}, $RECORDS);
?>
<?php include "public/views/pages/portal/account/structures/html_headings.phtml" ?>

<title>Dashboard</title>

<?php include "public/views/pages/portal/account/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/portal/account/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/portal/account/structures/html_navbar.phtml" ?>

</div>

<div class="right-content">

    <?php include "public/views/pages/portal/account/structures/html_right_heading.phtml" ?>

    <div class="right-body">

        <div class="data-table-main-container">
            <div class="data-table-header">
                <div class="left">
                    <div class="text">
                        <p>WALK IN</p>
                    </div>
                </div>
                <div class="right">
                    <div class="button-flex table-buttons">
                        <div class="text-button filled-button table-button show-component" data-name="delete-request">
                            <div class="text">
                                <span>REMOVE</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="edit-request">
                            <div class="text">
                                <span>VIEW</span>
                            </div>
                        </div>
                        <div class="text-button filled-button table-button show-component" data-name="add-request">
                            <div class="text">
                                <span>ADD</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="data-table-body">
                <?= CreateTable($WALKIN_TABLE_HEADER_TEXT, $WALKIN_TABLE_BODY_TEXT, $RECORDS, $ID, $BUTTON) ?>
            </div>
        </div>

    </div>

    <?php include "public/views/pages/portal/account/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/main/admin/walkin.js"></script>

    <?php include "public/views/pages/portal/account/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/portal/account/structures/html_body_closing.phtml" ?>
