<?php
global $APPLICATION;


?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Add New Account</h1>
                </div>
                <div class="paragraph">
                    <p>Create new account</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group">
                            <label for="">
                                <span>Firstname</span>
                            </label>
                            <div class="error-container">
                                <input type="text" name="firstname" placeholder="Firstname" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">
                                <span>Lastname</span>
                            </label>
                            <div class="error-container">
                                <input type="text" name="lastname" placeholder="Lastname" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group">
                            <label for="">
                                <span>Username</span>
                            </label>
                            <div class="error-container">
                                <input type="text" name="username" placeholder="Username" >
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">
                                <span>Password</span>
                            </label>
                            <div class="error-container">
                                <input type="password" name="password" placeholder="Password" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">
                            <span>Email Address</span>
                        </label>
                        <div class="error-container">
                            <input type="text" name="email_address" placeholder="Email Address" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">
                            <span>Mobile</span>
                        </label>
                        <div class="error-container">
                            <input type="text" name="mobile" placeholder="Mobile Number" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">
                            <span>Gender</span>
                        </label>
                        <div class="error-container">
                            <?= CreateComboBox("gender", "Gender", ["Male", "Female"], false, null, true) ?>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Confirm">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>