<?php
global $APPLICATION;

$control = $APPLICATION->FUNCTIONS->PACKAGE_CONTROL;

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Upload Images</h1>
                </div>
                <div class="paragraph">
                    <p>Drag & Drop images to upload!</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="drag-and-drop-files-container">
                        <input type="file" class="file" multiple="multiple" accept="image/jpeg, image/png, image/jpg" hidden>
                        <output></output>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Confirm">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>