<div class="main-list-list">
        <li class="item">
            <a href="/portal/profile">
                <div class="item-content">
                    <div class="left">
                        <div class="text">
                            <span>Your Profile</span>
                        </div>
                    </div>
                </div>
            </a>
        </li>

    <li class="item">
        <a href="/portal/logout">
            <div class="item-content">
                <div class="left">
                    <div class="text">
                        <span>Logout</span>
                    </div>
                </div>
            </div>
        </a>
    </li>
</div>