<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="/public/assets/styles/css/styles.css">
    <title>Document</title>
</head>
<body>
<div class="main-auth-container">
    <div class="top">
        <div class="logo">
            <?= UseImageWithSize('img/logo.png',100,80, true); ?>
        </div>
    </div>

    <div class="bot">
        <div class="auth-container for-register">
            <div class="right">
                <div class="main-form">
                    <form action="" class="form-control">
                        <div class="head">
                            <h3>Sign Up</h3>
                            <p>Create your account</p>
                        </div>
                        <div class="body">
                            <div class="form-group-container flex">
                                <div class="form-group">
                                    <label for="">
                                        <span>Firstname</span>
                                    </label>
                                    <div class="error-container">
                                        <input type="text" placeholder="Firstname" name="firstname">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="">
                                        <span>Lastname</span>
                                    </label>
                                    <div class="error-container">
                                        <input type="text" placeholder="Lastname" name="lastname">
                                    </div>
                                </div>
                            </div>


                            <div class="form-group-container flex">
                                <div class="form-group">
                                    <label for="">
                                        <span>Mobile</span>
                                    </label>
                                    <div class="error-container">
                                        <input type="text" placeholder="Mobile" name="mobile">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="">
                                        <span>Gender</span>
                                    </label>
                                    <div class="error-container">
                                        <div class="radios">
                                            <div class="radio">
                                                <input type="radio" id="male" name="gender" checked value="1">
                                                <label for="male">
                                                    Male
                                                </label>
                                            </div>

                                            <div class="radio">
                                                <input type="radio" id="female" name="gender" value="2">
                                                <label for="female">
                                                    Female
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group-container flex">
                                <div class="form-group">
                                    <label for="">
                                        <span>Username</span>
                                    </label>
                                    <div class="error-container">
                                        <input type="text" placeholder="Username" name="username">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="">
                                        <span>Password</span>
                                    </label>
                                    <div class="error-container">
                                        <input type="text" placeholder="Password" name="password">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="footer">
                            <div class="form-group-container flex submit-group">
                                <a href="/portal/auth/login" style="text-decoration: none; color: #000000">
                                    <div class="form-group">
                                        <div class="text-button">
                                            <span>BACK</span>
                                        </div>
                                    </div>
                                </a>
                                <div class="form-group">
                                    <input type="submit"  value="CREATE ACCOUNT">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="left" style="background-image: url('<?= UseImage('img/img2.jpg')  ?>');">

            </div>
        </div>
    </div>
</div>
</body>

<script src="/public/assets/scripts/pages/auth/register.js" type="module"></script>

</html>